### ISSUE TITLE
Doesn't work with BubbleUpnP

### ISSUE THREAD

**Issue by resom78** [dheijl/swyh-rs#18] opened 2020-11-14 09:19 UTC
Hi,

I tried your software with a chromecast emulated as a Openhome renderer via BubbleUpnP server.
The problem is that the device is not listed as renderer...
Second problem: I am unable to choose the audio capture source, by default it uses always the Conexant HD device.
I would rally like to use your app which looks really promising!

Thanks for your help

**Comment by dheijl** [comment] 2020-11-14 12:01
- First problem: could be a firewall problem, and network discovery should be enabled. The application should also be allowed inbound network access in the firewall, normally you are prompted by the firewall to allow this on the first start. SSDP is used for renderer discovery (UDP broadcast). The same goes for BubblUPNP.

- Second problem: only output audio sources that are *enabled* in the Windows audio control panel are listed, can you check this?

In theory what you are trying to do should work, so I'll do my best to help you make it work.
Enabling debug log level and posting the log file contents here could also be useful.

**Comment by dheijl** [comment] 2020-11-15 13:06
The problem is that BubbleUPNP does not respond to SSDP MSEARCH broadcast messages that search for RenderingControl or AVTransport devices, so it will never be detected. 
It only responds to "upnp:rootdevice" MSEARCH messages, which is useless because it causes a flood of SSDP responses by all devices in the network, and then *all* of them have to be queried one by one for supported services to see if they support OpenHome or AVTransport... (this inludes for instance all the lamps connected to a Philips Hue bridge, all routers, printers, wifi access points, settop boxes, you name it).

**Comment by dheijl** [comment] 2020-11-15 15:15
With a bit of assistance of Bubblesoft it does work now in V1.0.2! 
But only as a DLNA device, not an OpenHome device, but this makes no difference in use with swyh-rs.

Is this an acceptable solution?

**Comment by resom78** [comment] 2020-11-15 17:36
Yes it is perfect!! thanks a lot for this!
    Le dimanche 15 novembre 2020 à 16:16:01 UTC+1, dheijl <notifications@github.com> a écrit :  
 
 


With a bit of assistance of Bubblesoft it does work now in V1.0.2!
But only as a DLNA device, not an OpenHome device, but this makes no difference in use with swyh-rs.

Is this an acceptable solution?

**Comment by resom78** [comment] 2020-11-15 17:55
Hi again,
Now it works perfectly with a chromecast, but the problem of audio source selection is still there...
I use Virtual audio cable as default audio output in windows mixer, but the only source available in swyh-rs is the conexant (default sound card).
When I try with Local Audio Broadcast it works with the Virtual Audio Cable but I would prefer to use your software!

**Comment by resom78** [comment] 2020-11-15 17:57
Here is a copy of the log:
17:56:04 [INFO] swyh-rs Logging started.
17:56:04 [WARN] tb_log: *W*W*>Running DEBUG build => log level set to DEBUG!
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices: Supported hosts:
  [Wasapi]
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices: Available hosts:
  [Wasapi]
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices: WASAPI
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:   Default Output Device:
    Some("CABLE Input (VB-Audio Virtual Cable)")
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:   Devices:
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:   1. "Casque (Dynaudio Xeo 2 | Red   Stereo)"
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:     All supported output stream configs:
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:       1.1. SupportedStreamConfigRange { channels: 2, min_sample_rate: SampleRate(44100), max_sample_rate: SampleRate(44100), buffer_size: Unknown, sample_format: F32 }
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:     Default output stream config:
      SupportedStreamConfig { channels: 2, sample_rate: SampleRate(44100), buffer_size: Unknown, sample_format: F32 }
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:   2. "Haut-parleurs (Conexant SmartAudio HD)"
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:     All supported output stream configs:
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:       2.1. SupportedStreamConfigRange { channels: 2, min_sample_rate: SampleRate(44100), max_sample_rate: SampleRate(44100), buffer_size: Unknown, sample_format: F32 }
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:     Default output stream config:
      SupportedStreamConfig { channels: 2, sample_rate: SampleRate(44100), buffer_size: Unknown, sample_format: F32 }
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:   3. "CABLE Input (VB-Audio Virtual Cable)"
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:     All supported output stream configs:
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:       3.1. SupportedStreamConfigRange { channels: 2, min_sample_rate: SampleRate(44100), max_sample_rate: SampleRate(44100), buffer_size: Unknown, sample_format: F32 }
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:     Default output stream config:
      SupportedStreamConfig { channels: 2, sample_rate: SampleRate(44100), buffer_size: Unknown, sample_format: F32 }
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:   4. "CABLE Output (VB-Audio Virtual Cable)"
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:   5. "Mixage stéréo (Conexant SmartAudio HD)"
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:   6. "Microphone (Conexant SmartAudio HD)"
17:56:04 [DEBUG] (1) swyh_rs: Selected audio source: Haut-parleurs (Conexant SmartAudio HD)
17:56:04 [INFO] tb_log: Setup audio sources
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices: Supported hosts:
  [Wasapi]
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices: Available hosts:
  [Wasapi]
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices: WASAPI
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:   Default Output Device:
    Some("CABLE Input (VB-Audio Virtual Cable)")
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:   Devices:
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:   1. "Casque (Dynaudio Xeo 2 | Red   Stereo)"
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:     All supported output stream configs:
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:       1.1. SupportedStreamConfigRange { channels: 2, min_sample_rate: SampleRate(44100), max_sample_rate: SampleRate(44100), buffer_size: Unknown, sample_format: F32 }
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:     Default output stream config:
      SupportedStreamConfig { channels: 2, sample_rate: SampleRate(44100), buffer_size: Unknown, sample_format: F32 }
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:   2. "Haut-parleurs (Conexant SmartAudio HD)"
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:     All supported output stream configs:
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:       2.1. SupportedStreamConfigRange { channels: 2, min_sample_rate: SampleRate(44100), max_sample_rate: SampleRate(44100), buffer_size: Unknown, sample_format: F32 }
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:     Default output stream config:
      SupportedStreamConfig { channels: 2, sample_rate: SampleRate(44100), buffer_size: Unknown, sample_format: F32 }
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:   3. "CABLE Input (VB-Audio Virtual Cable)"
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:     All supported output stream configs:
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:       3.1. SupportedStreamConfigRange { channels: 2, min_sample_rate: SampleRate(44100), max_sample_rate: SampleRate(44100), buffer_size: Unknown, sample_format: F32 }
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:     Default output stream config:
      SupportedStreamConfig { channels: 2, sample_rate: SampleRate(44100), buffer_size: Unknown, sample_format: F32 }
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:   4. "CABLE Output (VB-Audio Virtual Cable)"
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:   5. "Mixage stéréo (Conexant SmartAudio HD)"
17:56:04 [DEBUG] (1) swyh_rs::utils::audiodevices:   6. "Microphone (Conexant SmartAudio HD)"
17:56:04 [INFO] tb_log: Now running at ABOVE_NORMAL_PRIORITY_CLASS
17:56:04 [DEBUG] (1) swyh_rs: Try capturing system audio
17:56:04 [INFO] tb_log: Capturing audio from: Haut-parleurs (Conexant SmartAudio HD)
17:56:04 [INFO] tb_log: Default audio SupportedStreamConfig { channels: 2, sample_rate: SampleRate(44100), buffer_size: Unknown, sample_format: F32 }
17:56:05 [INFO] tb_log: The streaming server is listening on http://192.168.1.16:5901/stream/swyh.wav
17:56:05 [INFO] tb_log: Running SSDP discovery
17:56:05 [DEBUG] (3) tiny_http: Server listening on 192.168.1.16:5901
17:56:05 [DEBUG] (6) swyh_rs::openhome::avmedia: SSDP discovery started
17:56:05 [DEBUG] (7) tiny_http: Running accept thread
17:56:06 [DEBUG] (6) swyh_rs::openhome::avmedia: UDP response at 504 from 192.168.1.16:58209:
HTTP/1.1 200 OK
Ext:
St: urn:schemas-upnp-org:service:RenderingControl:1
Server: Windows10/10.0 UPnP/1.0 BubbleUPnPServer/0.9-update38
Usn: uuid:c455753c-7412-7f09-0000-0000080059b1::urn:schemas-upnp-org:service:RenderingControl:1
Cache-control: max-age=1800
Location: http://192.168.1.16:60503/dev/c455753c-7412-7f09-0000-0000080059b1/desc.xml


17:56:06 [INFO] SSDP discovery: new Renderer found at : http://192.168.1.16:60503/dev/c455753c-7412-7f09-0000-0000080059b1/desc.xml
17:56:08 [DEBUG] (6) swyh_rs::openhome::avmedia: Getting new renderer descriptions
17:56:08 [DEBUG] (6) swyh_rs::openhome::avmedia: Get service description for http://192.168.1.16:60503/dev/c455753c-7412-7f09-0000-0000080059b1/desc.xml
17:56:08 [DEBUG] (6) swyh_rs::openhome::avmedia: Service description:
17:56:08 [DEBUG] (6) swyh_rs::openhome::avmedia: <?xml version="1.0" encoding="utf-8" standalone="yes"?><root xmlns="urn:schemas-upnp-org:device-1-0"><specVersion><major>1</major><minor>0</minor></specVersion><device><deviceType>urn:schemas-upnp-org:device:MediaRenderer:1</deviceType><UDN>uuid:c455753c-7412-7f09-0000-0000080059b1</UDN><friendlyName>Chromecast Olive (DLNA)</friendlyName><manufacturer>Bubblesoft</manufacturer><manufacturerURL>http://forum.xda-developers.com/showthread.php?t=1118891</manufacturerURL><modelDescription>BubbleUPnP Google Cast DLNA renderer</modelDescription><modelName>BubbleUPnP Google Cast DLNA renderer</modelName><modelNumber>0.9-update38</modelNumber><modelURL></modelURL><serialNumber>0.9-update38</serialNumber><presentationURL>http://192.168.1.16:58050</presentationURL><dlna:X_DLNADOC xmlns:dlna="urn:schemas-dlna-org:device-1-0">DMR-1.50</dlna:X_DLNADOC><iconList><icon><mimetype>image/png</mimetype><width>98</width><height>55</height><depth>32</depth><url>/dev/c455753c-7412-7f09-0000-0000080059b1/icon.png</url></icon></iconList><serviceList><service><serviceType>urn:schemas-upnp-org:service:AVTransport:1</serviceType><serviceId>urn:upnp-org:serviceId:AVTransport</serviceId><controlURL>/dev/c455753c-7412-7f09-0000-0000080059b1/svc/upnp-org/AVTransport/action</controlURL><eventSubURL>/dev/c455753c-7412-7f09-0000-0000080059b1/svc/upnp-org/AVTransport/event</eventSubURL><SCPDURL>/dev/c455753c-7412-7f09-0000-0000080059b1/svc/upnp-org/AVTransport/desc.xml</SCPDURL></service><service><serviceType>urn:schemas-upnp-org:service:RenderingControl:1</serviceType><serviceId>urn:upnp-org:serviceId:RenderingControl</serviceId><controlURL>/dev/c455753c-7412-7f09-0000-0000080059b1/svc/upnp-org/RenderingControl/action</controlURL><eventSubURL>/dev/c455753c-7412-7f09-0000-0000080059b1/svc/upnp-org/RenderingControl/event</eventSubURL><SCPDURL>/dev/c455753c-7412-7f09-0000-0000080059b1/svc/upnp-org/RenderingControl/desc.xml</SCPDURL></service><service><serviceType>urn:schemas-upnp-org:service:ConnectionManager:1</serviceType><serviceId>urn:upnp-org:serviceId:ConnectionManager</serviceId><controlURL>/dev/c455753c-7412-7f09-0000-0000080059b1/svc/upnp-org/ConnectionManager/action</controlURL><eventSubURL>/dev/c455753c-7412-7f09-0000-0000080059b1/svc/upnp-org/ConnectionManager/event</eventSubURL><SCPDURL>/dev/c455753c-7412-7f09-0000-0000080059b1/svc/upnp-org/ConnectionManager/desc.xml</SCPDURL></service></serviceList></device></root>
17:56:08 [DEBUG] (6) swyh_rs::openhome::avmedia: Renderer Chromecast Olive (DLNA) BubbleUPnP Google Cast DLNA renderer ip 192.168.1.16 at urlbase http://192.168.1.16:60503/ has 3 services
17:56:08 [DEBUG] (6) swyh_rs::openhome::avmedia:   => OpenHome Playlist control url: '', AvTransport url: '/dev/c455753c-7412-7f09-0000-0000080059b1/svc/upnp-org/AVTransport/action'
17:56:08 [DEBUG] (6) swyh_rs::openhome::avmedia: .. urn:schemas-upnp-org:service:AVTransport:1 urn:upnp-org:serviceId:AVTransport /dev/c455753c-7412-7f09-0000-0000080059b1/svc/upnp-org/AVTransport/action
17:56:08 [DEBUG] (6) swyh_rs::openhome::avmedia: .. urn:schemas-upnp-org:service:RenderingControl:1 urn:upnp-org:serviceId:RenderingControl /dev/c455753c-7412-7f09-0000-0000080059b1/svc/upnp-org/RenderingControl/action
17:56:08 [DEBUG] (6) swyh_rs::openhome::avmedia: .. urn:schemas-upnp-org:service:ConnectionManager:1 urn:upnp-org:serviceId:ConnectionManager /dev/c455753c-7412-7f09-0000-0000080059b1/svc/upnp-org/ConnectionManager/action
17:56:08 [DEBUG] (6) swyh_rs::openhome::avmedia: SSDP discovery complete
17:56:08 [INFO] Found new renderer Chromecast Olive (DLNA) BubbleUPnP Google Cast DLNA renderer  at 192.168.1.16
thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 3', src\main.rs:318:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src\main.rs:306:41

**Comment by dheijl** [comment] 2020-11-15 18:35
If you click on the dropdown for the audio source, do you see only 1 audio source instead of 3?

Or can you select one of the 3 available but the application panics when you slect one of them?

**Comment by resom78** [comment] 2020-11-15 19:01
Actually I can see the 3 audio sources but when I try to select one the app panics.
    Le dimanche 15 novembre 2020 à 19:35:19 UTC+1, dheijl <notifications@github.com> a écrit :  
 
 


If you click on the dropdown for the audio source, do you see only 1 audio source instead of 3?

Or can you select one of the 3 available but the application panics when you slect one of them?

**Comment by dheijl** [comment] 2020-11-16 13:37
Choosing the audio source should be fixed now in V1.03. It was caused by a "|" in a source name, it has a special meaning in FLTK menu_items.
And for Bubble you can now use OpenHome too (but you will have to delete the DLNA device manually first from the Bubble config xml).

**Comment by resom78** [comment] 2020-11-16 14:50
I've tested it and it works like a charm!
Thanks for everything, this app is now almost perfect (maybe the GUI?)!

**Comment by dheijl** [comment] 2020-11-16 15:10
Thanks for testing.

Meanwhile I fixed another bug in 1.0.4. As for the GUI...

**Closed** 2020-11-16 15:17 UTC
