### ISSUE TITLE
Autoreconnect does not work with multiple Sonos Devices

### ISSUE THREAD

**Issue by BBRXMusic** [dheijl/swyh-rs#129] opened 2024-04-19 16:56 UTC
I am testing with multiple Sonos Devices.  

SSDP Discovers the devices but will only connect to one, depending on the device from the pairing there will sometimes be no audio.  There will only be output on one of the two devices.

I can manually select both devices and everything works perfectly.  However upon restart autoconnect only connects to one device again.

**After selecting two devices.**
![image](https://github.com/dheijl/swyh-rs/assets/64019599/d5ee6855-e380-4136-9f25-13a6d78b83e3)

**After restart (back to one device)**
Depending on the device there may be no audio
![image](https://github.com/dheijl/swyh-rs/assets/64019599/d206fbd4-448e-4015-8c71-af8bf159368f)

If I try adding a custom radio station unchecking both devices and unchecking the "Autoreconnect" and 'Autoresume play"  I just get blasts of static/noise and no stable connection.

I have tried FLAC and WAV with all StreamSize options.

Ideally I would hope to be able to select any number of devices and have Autoconnect restore the connections to all of them.

**Comment by omoknen** [comment] 2024-04-19 17:22
I have a set of SONOS speakers, and the best way to get them to work together and stay in sync (if you don't have connections issues -Wireless can be finicky) with SWYH-RS is to use the SONOS application.  Generally SONOS is where I have had problems.

Using the SONOS PC app or the phone Apps....
1)  I created an entry using Tune-IN -> My Radio for SWYH-RS
2)  Make that entry a SONOS favorite.
3)  You need to group all the speakers together, and then select your SWYH-RS favorite.

I only problems with SONOS when they update.  Sometimes I have had to reboot the speakers.

**Comment by BBRXMusic** [comment] 2024-04-19 17:29
You're described setup is precisely what I was trying first.  This worked perfectly with the legacy(original) SWYH.  

wIth -RS the stream attempts to start, static or momentary audio distortion then disconnect as a continuous loop.

**Comment by omoknen** [comment] 2024-04-19 17:52
I am not the author, but it has been working for me.  I hope he can help you.  I do see some difference (Windows 10)
I use the virtual cable (VB-Audio Virtual Cable) driver he recommends, and then I redirect the audio directly from Music Application to the virtual cable (MusicBee).   It works for everything if you make the Virtual Cable as the default speaker, but it will always lag at the pc so I separated it.

**Comment by BBRXMusic** [comment] 2024-04-19 18:42
Same issue with VB-Cable.  .wav stream picked up, brief connections and disconnect, audio cuts out.
SSDP works perfectly but the system will not auto-connect to multiple devices on restart

**Comment by BBRXMusic** [comment] 2024-04-19 18:53
As an additional note if I use VLC to test the http streams I can pickup FLAC and VLC fine.  It is specifically the Sonos ERA 100 group that cannot keeps dropping and producing brief periods (ms) of audio (per logs).  

Again if I go to the old SWYH project and stream as .mp3 everything works perfectly, but I would prefer a  solution that can inject silence.  

For the other project I had to write my own program to run on startup and generate a continuous 2hz sample to keep the stream alive.

**Comment by dheijl** [comment] 2024-04-20 12:15
At present swyh-rs can only autoconnect to a single device, and that is the last one activated.

**Comment by BBRXMusic** [comment] 2024-04-20 16:11
Thanks @dheijl   unfortunately I'm still not sure why whether using VB-Cable or direct the speakers cannot connect via "Custom Radio Station" with swyh-rs, only SSDP.  I'm not sure if there is a conflict there.

I couldn't find any switch do disable SSDP.

**Comment by dheijl** [comment] 2024-04-20 18:26
I don't own any Sonos speakers, so I have to rely on information I receive.

There is no relationship between  SSDP and using swyh-rs as a radio station, it should just work if you provide rhe correct URL.

If it doesn't work, the only thing that can help me diagnosing the problem is if you 
- enable debug logging in swyh-rs and restart swyh-rs
- try to connect using the custom radio station url
- stop swyh-rs
- upload the resulting log.txt here from the .swyh-rs folder in your home directory

**Comment by dheijl** [comment] 2024-04-20 18:30
It is possible to disable ssdp if you use the cli exe with the -x (serve only) switch, but somehow I don't  think it's going to help you here.

**Comment by BBRXMusic** [comment] 2024-04-22 14:00
Hi @dheijl,

Please find the log attached.  

[log.txt](https://github.com/dheijl/swyh-rs/files/15064014/log.txt)

**Comment by omoknen** [comment] 2024-04-22 17:17
Sorry for adding some more information this late, but I hope this might help you.

I hadn't realized that Era 100's are all wireless, my Sonos One's are now all wired because I had wireless problems (my sonos prefer hardwired ethernet).

You might be able to use this on your web browser.  I had a Sonos Community link but they removed it so I don't know if it still works with Era 100's.  (It has to be http not https)

http://***.***.***.***:1400/support/review

You then want to look at the "Network Matrix" link to see the signal strength and which unit is acting as the root bridge.

**Comment by dheijl** [comment] 2024-04-22 19:52
The internet radio url /swyh.**flac** always assumes 24 bit, the other ones 16 bit. If the configured value does not match this the streaming headers do not match the actual data and you will get garbage. It's a limitation. Just like the single autoreconnect player and the lack of mp3 support.

**Comment by BBRXMusic** [comment] 2024-04-22 21:49
I have tested the URL's as you specified above (24Bit selected for FLAC, 16Bit for WAV) same results.  

Of note I can pickup the streams on a mobile device and VLC with no issue.  It's specifically an issue with the Sonos ERA-100 pair.  

Again, what I find odd is SSDP works perfectly, unfortunately the single device selection on restart is a blocker here, as there is only 1 channel of audio after a restart and the playback source is headless so no convenient way to select the devices after a restart.

**Comment by dheijl** [comment] 2024-04-22 22:18
Are you using swyh-rs Gui? In that case supporting reconnect to multiple devices on startup should be relatively easy.

**Comment by BBRXMusic** [comment] 2024-04-22 22:34
I am using the GUI so if we could maintain an array of "Active or Selected" renderer in the config rather than just last renderer for auto_reconnect that would be great

**Comment by dheijl** [comment] 2024-04-23 10:33
It will be in 1.10.4, within a few days I hope.

**Comment by dheijl** [comment] 2024-04-23 15:06
It should work now from the GUI with [1.10.4](https://github.com/dheijl/swyh-rs/releases/tag/1.10.4). 
**Any player still playing** when you close swyh-rs GUI will be remembered in the config file before stopping it and it will be restarted when swyh-rs restarts with autoreconnect on.

**Comment by BBRXMusic** [comment] 2024-04-23 17:05
Thanks @dheijl 

This seems to be working well.  I have it in the shell:startup and for whatever reason the first couple restarts SSDP discovery was failing after selecting the devices and rebooting or restarting.

It seems to have stabilized; I can now reboot the system or close and relaunch swyh-rs and playback resumes

[log.txt](https://github.com/dheijl/swyh-rs/files/15080295/log.txt)

**Comment by dheijl** [comment] 2024-04-23 17:53
> I have it in the shell:startup...

It is dependent on the network being fully initialized before you start it, perhaps that is why the SSDP discovery sometimes fails in the shell::startup after a reboot?

**Comment by BBRXMusic** [comment] 2024-04-23 18:04
It could be.  I will wrap it in another launcher that will check the network status and test the active_renderers from the config before launching.

**Comment by dheijl** [comment] 2024-05-04 16:07
I suppose this can be closed now? You can always reopen if needed.

**Closed by dheijl** 2024-05-04 16:07 UTC
