### ISSUE TITLE
FLAC support for Sonos?

### ISSUE THREAD

**Issue by Max3651** [dheijl/swyh-rs#73] opened 2022-08-29 19:19 UTC
No matter what I’ve tried, FLAC doesn’t work on Sonos. This isn’t really an issue but I do feel if you can find a workaround it can help lower the latency and bring native 24 bit support as .wav gets downscaled to 16 bit with Sonos speakers.

**Comment by dheijl** [comment] 2022-09-01 12:42
The problem is that I don't have Sonos, so I can't test/debug this issue to try and find a solution...

**Comment by dheijl** [comment] 2023-02-25 10:44
Sonos does not support flac over dlna, so I am closing this.

**Closed by dheijl** 2023-02-25 10:44 UTC
