### ISSUE TITLE
Old / corrupted config.toml causes program to panic

### ISSUE THREAD

**Issue by FinalSh4re** [dheijl/swyh-rs#50] opened 2021-12-08 11:26 UTC
Hello!

After updating swyh-rs for the first time in months it wouldn't start anymore. The backtrace revealed that it panicked trying to load my old config.toml created by the previous version (which had less entries than the current one).  

I noticed that at the moment the program only checks for an existing 'config.ini' and migrates its contents to a new config.toml file, however as long as a file with name 'config.toml' exists it doesn't check its validity. 

The program panics [here](https://github.com/dheijl/swyh-rs/blob/master/src/utils/configuration.rs#L107) at the `.unwrap()` since de-serializing fails when the toml file is missing some fields (or is otherwise corrupted).

A quick fix should be implementing the `Default` trait for `Config`:

```py
impl Default for Config {
    fn default() -> Self {
        Config { configuration: Configuration::default() }
    }
}
```

and then calling `.unwrap_or_default()` instead of `.unwrap()`:

```py
let mut config: Config = from_str(&s).unwrap_or_default();
```

However, considering that the old ini files also get migrated the preferred behavior would be trying to recover as many values as possible from the old file and only updating the missing fields with their respective default values, no?

**Comment by dheijl** [comment] 2021-12-08 12:39
I must have overlooked a newly added value, nely added values should be an Option precisely for that reason

**Comment by FinalSh4re** [comment] 2021-12-08 12:42
Good to know, I didn't dig too deeply into the source code. The old config was missing the ServerPort field.

**Comment by dheijl** [comment] 2021-12-08 12:44
Thanks! But I can't imagine that value missing, it has been there since the beginning... Unless the toml file was manually edited or corrupted in some way.

**Comment by FinalSh4re** [comment] 2021-12-08 12:47
Hmm this is strange, as far as I remember I didn't manually change anything in the config.

**Comment by FinalSh4re** [comment] 2021-12-08 12:51
Okay, I checked. The old cofig.toml was generated by version 1.3.12. I had a quick look at the code, I doesn't seem to set the ServerPort field.

**Comment by dheijl** [comment] 2021-12-08 12:52
This is the cause of the bug then, thanks!

**Comment by FinalSh4re** [comment] 2021-12-08 13:02
This explains it then. On a side note, wouldn't checking the file's integrity (at least) as a fail safe still be a good idea in case the config gets corrupted through external influences?

**Comment by dheijl** [comment] 2021-12-08 14:21
I'll fix the serverport panic when upgrading from pre-1.3.13, but checking integrity seems a bit overkill to me. I'll document this though, as the panic is easily fixed by simply deleting the corrupt toml file. 
And thanks for taking the trouble to figure this out!

**Closed** 2021-12-08 14:46 UTC
